### ISSUE TITLE
children of the emitter and a bug

### ISSUE THREAD

**Issue by Megabalta** [GlyphXTools/particle-editor#3] opened 2017-06-15 17:43 UTC
1. working with more than one child emitters (cutting/deleting) crashes the editor when playing the particle (shift), if saved before crashing the particle file can't be opened again

2. pasting a child emitter to a parent, closing-reopening the file sometimes puts it to a false parent emitter

3. child emitter layer is behind the parent emitter layer when played in the particle editor, however is always in front of the parent emitter when played ingame. This might be an exporting issue. I'd greatly appreciate if the editor would export the emitter layer order just like it's seen in the editors preview (always parent in front of child) to achieve the same effect seen on this picture - from the editor - ingame

![epic1](https://user-images.githubusercontent.com/29461825/27194230-20e9ca20-5202-11e7-99d4-498a39ba229c.jpg)

4. Appearance - Fixed random rotation: every time a particle file is reopened in the particle editor, the second (+-) value gets down by one. It's really annoying, when you're constantly changing (thus reopening) files you work with.

**Comment by Shimrra** [comment] 2017-06-15 18:40
2/3 are possible duplicates of #2

**Comment by MikeLankamp** [comment] 2017-06-17 13:57
@Megabalta, for items 1 and 2, can you download the latest build from the project page and give exact reproduction steps to get a crash or incorrect behavior?

**Comment by Megabalta** [comment] 2017-06-17 16:50
@MikeLankamp it seems to be working right now, although I couldn't test pasting child emitters due to 1.5.b3.

v1.5 (32 bit) has 5 bugs I've discovered btw.

1.5.b1. won't remember game directory, needs input at every start
1.5.b2. description says add EaW-Forces of Corruption directory, but to display textures the program really needs the EaW *game directory*/GameData directory, so not that of the expansion (in Empire at War Gold)
1.5.b3. missing right click menu on the emitters panel, which makes pasting child emitters impossible (no other menu has the option)
1.5.b4. missing icon textures (for new emitter, delete emitter etc.) above Basic-Appearance-Physics tabs
1.5.b5. missing icons for emitter types (bursts, continuous stream, weather) in emitter panel

**Comment by MikeLankamp** [comment] 2017-06-17 17:16
I already fixed bugs 1.5b4 and 1.5b5 (missing icons). 

This issue has now become a collection of several bugs. It's generally good practice to have one issue per bug, otherwise it gets hard to track what's happening, so I'm going to close this one for that reason. 

@Megabalta, please create a new issue for each of the remaining new bugs, as well as for the original bugs in this issue that haven't been fixed yet (i.e. 1, 2 and 4; 3 indeed seems a duplicate of #2).

**Closed as completed by MikeLankamp** 2017-06-17 17:16 UTC
